#!/bin/sh
# $Id$
# elvis: atypbug		-- Show bugzilla bug by id
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw show bug by id on custom bugzilla
EOF
    w3_global_usage
}

MY_BUGZILLA_URL="XXXX"
w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "$MY_BUGZILLA_URL"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "$MY_BUGZILLA_URL/show_bug.cgi?id=${escaped_args}"
fi
