#!/bin/sh
# $Id$
# elvis: deviantart		-- Search deviantart (www.deviantart.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw show bug by id on custom bugzilla
EOF
    w3_global_usage
}

DAURL="http://www.deviantart.com/browse/all"
w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "$DAURL"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "$DAURL/?qh=&section=&global=1&q=${escaped_args}"
fi
